### ISSUE TITLE
Lazy-loading of results in GUI

### ISSUE THREAD

**Issue by tastott** [tastott/jsoql#78]

**Comment by tastott** [comment]
Had some promising results using [ng-infinite-scroll](https://sroze.github.io/ngInfiniteScroll/) but looks like it only works with window scroll (not container). Might be able to make it work with something like [this](https://jsfiddle.net/kL9e449q/)

**Comment by steven-dawkins** [comment]
How about a simple more button like google images?

![image](https://cloud.githubusercontent.com/assets/809363/8156193/daedb6b2-1342-11e5-8002-84a4bbebf354.png)
